"""
Pydantic schemas for Process Decomposer Agent.
Adheres to the architectural specification for Phase 6.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from app.schemas.requirement import RequirementAnalysis


class PlannedStep(BaseModel):
    id: str = Field(..., description="Planned step ID (e.g. step_1)")
    name: str = Field(..., description="Human readable step name")
    description: str
    stage: str = Field(..., description="Process stage (e.g. Intake, Verification, Approval, Fulfillment)")
    category: str = Field(..., description="database, rag, decision, notification, approval, transform, trigger, end")
    dependencies: List[str] = Field(default_factory=list)
    expected_inputs: List[str] = Field(default_factory=list)
    expected_outputs: List[str] = Field(default_factory=list)
    requires_human: bool = False
    is_critical: bool = True


class ProcessStage(BaseModel):
    name: str
    order: int
    description: Optional[str] = None
    step_ids: List[str] = Field(default_factory=list)


class ToolRequirement(BaseModel):
    tool_name: str
    action: str
    purpose: str


class ProcessPlan(BaseModel):
    """Structured high-level process plan generated by Process Decomposer Agent."""
    process_name: str
    summary: str
    stages: List[ProcessStage] = Field(default_factory=list)
    steps: List[PlannedStep] = Field(default_factory=list)
    tool_requirements: List[ToolRequirement] = Field(default_factory=list)
    data_flow_summary: Dict[str, List[str]] = Field(default_factory=dict)
    estimated_duration_seconds: int = Field(default=120)


class DecomposeProcessRequest(BaseModel):
    analysis: RequirementAnalysis
    max_stages: Optional[int] = Field(default=6, ge=2, le=10)


class DecomposeProcessResponse(BaseModel):
    status: str = "success"
    plan: ProcessPlan
    warnings: List[str] = Field(default_factory=list)
