"""
Pydantic schemas for Requirement Analysis agent.
Adheres to the architectural specification for Phase 5.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class BusinessRule(BaseModel):
    rule_id: str
    description: str
    condition: Optional[str] = None
    action: Optional[str] = None


class Actor(BaseModel):
    role: str
    type: str = "human"  # human, system, agent
    responsibilities: List[str] = Field(default_factory=list)


class ApprovalCriteria(BaseModel):
    role: str
    trigger_condition: str
    rationale: str


class RequirementAnalysis(BaseModel):
    """Structured analysis output generated by Requirement Analyzer Agent."""
    business_goal: str = Field(..., description="High level goal of the business workflow")
    trigger_event: str = Field(..., description="Event or condition that initiates the process")
    trigger_description: str = Field(..., description="Details of how the workflow is triggered")
    inputs: List[Dict[str, Any]] = Field(default_factory=list, description="Required inputs from trigger or user")
    outputs: List[str] = Field(default_factory=list, description="Expected business outputs")
    actors: List[Actor] = Field(default_factory=list, description="Actors involved in the process")
    business_rules: List[BusinessRule] = Field(default_factory=list, description="Explicit and inferred rules")
    data_entities: List[str] = Field(default_factory=list, description="Core business entities manipulated")
    approval_requirements: List[ApprovalCriteria] = Field(default_factory=list, description="Human approval steps required")
    potential_exceptions: List[str] = Field(default_factory=list, description="Edge cases and failure scenarios")
    complexity_assessment: str = Field(default="Moderate", description="Simple, Moderate, or Complex")
    confidence_score: float = Field(default=0.95, ge=0.0, le=1.0)


class AnalyzeRequirementRequest(BaseModel):
    requirement_text: str = Field(..., min_length=10, max_length=10000, description="Raw natural language requirement")
    domain_hint: Optional[str] = None
    additional_context: Optional[Dict[str, Any]] = None


class AnalyzeRequirementResponse(BaseModel):
    status: str = "success"
    analysis: RequirementAnalysis
    warnings: List[str] = Field(default_factory=list)
